name: np_finanzas_ia
description: N|P Finanzas IA - Tu asistente inteligente para entender, organizar y mejorar tus finanzas.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  intl: ^0.20.2
  supabase_flutter: ^2.8.3   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true